### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by konshubl** [chloette/ffmpeg4android#3]
when I run ./build_android.sh, I am getting the following output
----
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
/Users/eyan/Downloads/ffmpeg4android/ffmpeg-2.7.2/../../android-ndk-r10/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

----

my build script is:

NDK=$NDK_HOME
SYSROOT=$NDK/platforms/android-9/arch-arm/
TOOLCHAIN=$NDK/toolchains/arm-linux-androideabi-4.8/prebuilt/
if [ -d "$TOOLCHAIN/linux-x86_64" ]; then
  TOOLCHAIN+=linux-x86_64
else #treat as darwin
  TOOLCHAIN+=darwin-x86_64
fi
function build_one
{
./configure \
    --prefix=$PREFIX \
    --enable-shared \
    --disable-static \
    --disable-doc \
    --disable-ffmpeg \
    --disable-ffplay \
    --disable-ffprobe \
    --disable-ffserver \
    --disable-avdevice \
    --disable-doc \
    --disable-symver \
    --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
    --target-os=linux \
    --arch=arm \
    --disable-debug \
    --enable-gpl \
    --enable-cross-compile \
    --sysroot=$SYSROOT \
    --extra-cflags="-Os -fpic $ADDI_CFLAGS"  \
    --extra-ldflags="$ADDI_LDFLAGS -s" \
    $ADDITIONAL_CONFIGURE_FLAG

#make clean
#make
#make install
}
CPU=arm
PREFIX=$(pwd)/android/$CPU 
ADDI_CFLAGS="-marm"
build_one

-------
Any help would be appreciated.

**Comment by chloette** [comment]
May I ask you one question?

Have you ever downloaded and configed NDK first?

**Comment by konshubl** [comment]
Yup I did. Wouldn't it output, file/directory not found if I didn't have the NDK anyways?

**Comment by chloette** [comment]
Sorry to replay so late..

Your make file looks good, i'm not sure why not the configure failed:
/Users/eyan/Downloads/ffmpeg4android/ffmpeg-2.7.2/../../android-ndk-r10/
toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
is unable to create an executable file.

Can you check what you got if you input 'echo $NDK_HOME' in a terminal? (It
seemsthe environment was not set correctly.)

Thanks,
E

**Comment by konshubl** [comment]
Edwards-MBP:ffmpeg-2.7.2 eyan$ echo $NDK_HOME
/Users/eyan/Downloads/android-ndk-r10

it echoes the value as expected. Any other ides? Big head scratching moment for me =/

**Comment by chloette** [comment]
Yes, NDK_HOME looks good.
Can you check whether this folder exists?
$NDK_HOME/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/
And one more thing, is arm-linux-androideabi-gcc executable?

**Comment by konshubl** [comment]
There wasn't a arm-linux-androideabi-4.8, but there is a 4.9. I changed the build script to reflect the folder properly, however the build still fails the same way.

I ran "ls -l" in a terminal in the directory and it gave me "-rwxr-xr-x", since there is an x it is executable.

**Comment by chloette** [comment]
same error log? Please show me the newer error logs.

**Comment by konshubl** [comment]
Finally got it to compile right. The issue was that somehow I had downloaded a r10 version that only had /platforms/android-L (I really should have checked these folders). I re-downloaded the NDK (v. r10e) and now it works like a charm. Everything compiles and generates the .SO files. Thank you for the help. I really should have been more careful checking the directories better.
