### ISSUE TITLE
libmp3lame support

### ISSUE THREAD

**Issue by konshubl** [chloette/ffmpeg4android#4]
Hi,
I was wondering if you are willing to write something up/support compiling libmp3lame with ffmpeg.

**Comment by chloette** [comment]
http://ffmpeg.org/ffmpeg-codecs.html#libmp3lame-1 this one？

**Comment by konshubl** [comment]
yes that one.

**Comment by chloette** [comment]
i think you can refer to another similar library already compiled into
ffmpeg4android -- x264~

**Comment by konshubl** [comment]
Are you referring to this? https://github.com/chloette/x264android

**Comment by chloette** [comment]
yes.

**Comment by konshubl** [comment]
That describes compiling it separate from ffmpeg, I was hoping there was a way to compile into ffmpeg and then add it to android project.

**Comment by chloette** [comment]
compile x264 to generate x264.a
then compile x264.a into ffmpeg.so

That's the way~

**Comment by chloette** [comment]
any progress?
